# .github/workflows/nodejs.yml
name: Node CI

on: [push, pull_request] # Run on Push and Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x] # Only run the 10.x build
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: Install Dependencies
      run: yarn install
    - name: Build
    - run: yarn build
    - name: Archive Produciton Artifacts
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
